### PR TITLE
Created Audit History feature 

### LINKED ISSUE #5: Audit History
We do have the functionality of updating and deleting in this application but maintaining the history of who has done this and at what time elapse it has been done, is missing. 

You can try doing it by going to the update functionality in 'controller. js'(it controls the entire backend) when the user is trying to update a column by ID, add a compulsory middleware, or maybe a function within 'exports. update' to include the name of the user who is trying to update and in the backend, we should have an audit history consisting of the name and time(we have javascript objects for date and time, can use that) at which it has been updated.
This same functionality must be included in the delete portion too. 

[https://learn.microsoft.com/en-us/power-apps/developer/data-platform/auditing/retrieve-audit-data?tabs=webapi](url)
Can read this to get more clarification.

### PR DESCRIPTION
**Pull request by reharsh**
such that whenever user performs update/delete ops an audit history containing userId,time,operation is being stored

## Description

I have created new collection for audit with schema like {userId, time, operation} this will be stored whenever user will perform any update/delete operation. Here userId is of type ObjectId ref to "user" and time is of type Date.Now(), which will return the current time when function is called.

## Related Issue

ISSUE #5 : https://github.com/ContriHUB/User-management-system/issues/5

Fixes #5 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

As this is the User Management System, in which users can perform several operations back and forth so, it is important to keep logs of operations and the history with proper attachment of user and time.

## How Has This Been Tested?

Tested by performing update and delete operations several times.

## Screenshots (if appropriate):
(UPDATED) Audit History with user's name, time stamp in readable format {dd:mm:yyyy  HH:MM:SS} and the operation performed.
image

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

#### Name: Harsh Kumar Meena https://sac.mnnit.ac.in/contrihub/profile/user/reharsh/

-   Place: Greater Noida, UP, INDIA
-   Bio: BTech 2nd Year, MNNIT
-   GitHub: https://github.com/reharsh

### CODE REVIEW

**Review by the-evocative-eye — CHANGES_REQUESTED** [review]
Where are you fetching this user ID from? or are you creating one?
Instead, try to fetch the name or maybe the email ID of the person which he/she must have used when logging in.

**Comment by reharsh** [comment]
> Where are you fetching this user ID from? or are you creating one? Instead, try to fetch the name or maybe the email ID of the person which he/she must have used when logging in.

Done. Now the "name" of user is being stored who had performed the operation instead of the userID
Screenshot is attached in PR.

**Review by the-evocative-eye — CHANGES_REQUESTED** [review]
The name is fine, but the way you have displayed time is quite unreadable to anybody, try to display it in the format (day, date, time(not in milliseconds at least). Ex:(Saturday, 14 October , 9:04  am)

**Comment by reharsh** [comment]
Done ma'am. Please let me know if any other changes are to be made.
(Screenshot is Updated)

**Comment by reharsh** [comment]
@the-evocative-eye  ma'am by mistake closed the PR, requested changes are done and Screenshot is updated, please let me know if any other changes are to be made. Thanks

**Review by the-evocative-eye — APPROVED** [review]

**Pull request merged**
