### PR TITLE
Implemented grouping of rows

### LINKED ISSUE #4: Grouping of rows
Screenshot (24)
Grouping the data with active status over inactive status, right now it is arranged based on first come, first serve.
This feature will ease the user readability. You can try doing it like this is the home page, so go to this home page.js->find how it is displaying data, and try applying the 'group by'(js query has this feature) based on active or inactive functionality to that data.

### PR DESCRIPTION
**Pull request by Manan-Arora31**
## Description

Earlier all the rows of the homepage appeared in the order of first come first serve basis . But now all the active rows appear as a group above all the inactive rows . 

## Related Issue

Fixes #4 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

It is required as it improves readability for the user. 

## How Has This Been Tested?

I ran the website on my local server and checked that the functionality is working properly.

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [ ] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by the-evocative-eye — CHANGES_REQUESTED** [review]
When you are checking for active status, you are not displaying all columns other than id and name, and also look to the number of curly braces used.

**Comment by Manan-Arora31** [comment]
@the-evocative-eye I am not able to get what changes you are saying . This is the code I have commited . All the columns are visible in this and there are no extra curly braces . Please clarify

Screenshot 2023-10-11 155203
Screenshot 2023-10-11 155214

**Comment by the-evocative-eye** [comment]
> @the-evocative-eye I am not able to get what changes you are saying . This is the code I have commited . All the columns are visible in this and there are no extra curly braces . Please clarify
> 
> Screenshot 2023-10-11 155203 Screenshot 2023-10-11 155214

Ohh Okay, sorry, my bad, one more thing, Id's would then not be arranged sequentially if you keep i+1 in ID and arrange it based on status, and we want IDs to be in order(1,2,3, and so on) even after arranging it based on status. Just try solving this issue too!

**Comment by Manan-Arora31** [comment]
Can I still work on this issue ? The time alloted to me is over

**Comment by the-evocative-eye** [comment]
Yes, please go ahead!

**Comment by Manan-Arora31** [comment]
@the-evocative-eye I have made the required changes. Please check.

**Review by the-evocative-eye — APPROVED** [review]

**Pull request merged**
